server.port: 8089

spring:
  profiles.active: dev
  cloud:
    gcp:
      project-id: sab-ors-poc-sbx-01-9096
      #credentials.location: file:C:\\Users\\SG0310427\\Downloads\\sab-ors-poc-sbx-01-9096-f8581ce293f7.json
      spanner:
        instance-id: instance-1
        database: database-1

app:
  topic.name: projects/sab-ors-poc-sbx-01-9096/topics/topic-1

